### PR TITLE
WIP: Training script

### PR DESCRIPTION
**Pull request by isamu-isozaki**
Hi! This is just the wip training script we had. I just added accelerate+cleaned db code so might be buggy but will clean it up tomorrow. 

Also, we did separate your one file code into multiple files. Happy to close this pr and make a new one where we just do the one-file thing too!

### CODE REVIEW

**Comment by isamu-isozaki** [comment]
Sry just noticed we also stopped making it a python module. Fixing today

**Comment by isamu-isozaki** [comment]
Ok. Fixed some things. Will clean up more+test in a bit

**Comment by isamu-isozaki** [comment]
Ok! Finished cleaning up the diffs. Now I'll try training+running

**Comment by isamu-isozaki** [comment]
@lucidrains Hi! Finished what I wanted for now. Let me know what you think! I tested out some training too.

**Comment by isamu-isozaki** [comment]
I'll add dataset download instructions etc

**Comment by lucidrains** [comment]
> @lucidrains Hi! Finished what I wanted for now. Let me know what you think! I tested out some training too.

looks great! graciously accepting! :pray:

**Comment by isamu-isozaki** [comment]
@lucidrains Glad you like it!

**Pull request merged**
